### ISSUE TITLE
Use a templating engine to generate the output file

### ISSUE THREAD

**Issue by thefinn93** [NateBrune/Creep#7]
This would make it more configurable and easier to change the layout, etc

**Comment by thefinn93** [comment]
I like [Jinja2](http://jinja.pocoo.org/) for templates, but I haven't looked that hard (just seems to be what everyone uses)

**Comment by NateBrune** [comment]
I agree, I was thinking about doing this as well. I was not aware of this type of thing when I started the project and it is probably the route I should have forgone. If I can I will do it this weekend. Shouldn't be very hard.

**Comment by thefinn93** [comment]
Starting this in d48a612
